CREATE TABLE  tests (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    task_id INTEGER NOT NULL,
    input VARCHAR(256) NOT NULL,
    expected_result VARCHAR(256) NOT NULL,
    points INTEGER NOT NULL
);